/**
 * Permission constants and role-based permission mappings for CreditNexus frontend.
 * 
 * These constants must match the backend permission system in app/core/permissions.py
 */

// Document Permissions
export const PERMISSION_DOCUMENT_CREATE = "DOCUMENT_CREATE";
export const PERMISSION_DOCUMENT_EDIT = "DOCUMENT_EDIT";
export const PERMISSION_DOCUMENT_DELETE = "DOCUMENT_DELETE";
export const PERMISSION_DOCUMENT_VIEW = "DOCUMENT_VIEW";
export const PERMISSION_DOCUMENT_REVIEW = "DOCUMENT_REVIEW";
export const PERMISSION_DOCUMENT_APPROVE = "DOCUMENT_APPROVE";
export const PERMISSION_DOCUMENT_EXPORT = "DOCUMENT_EXPORT";
export const PERMISSION_DOCUMENT_EXTRACT = "DOCUMENT_EXTRACT";

// Deal Permissions
export const PERMISSION_DEAL_CREATE = "DEAL_CREATE";
export const PERMISSION_DEAL_EDIT = "DEAL_EDIT";
export const PERMISSION_DEAL_DELETE = "DEAL_DELETE";
export const PERMISSION_DEAL_VIEW = "DEAL_VIEW";
export const PERMISSION_DEAL_VIEW_OWN = "DEAL_VIEW_OWN";
export const PERMISSION_DEAL_APPROVE = "DEAL_APPROVE";
export const PERMISSION_DEAL_REJECT = "DEAL_REJECT";
export const PERMISSION_DEAL_CLOSE = "DEAL_CLOSE";

// Trade Permissions
export const PERMISSION_TRADE_CREATE = "TRADE_CREATE";
export const PERMISSION_TRADE_EDIT = "TRADE_EDIT";
export const PERMISSION_TRADE_DELETE = "TRADE_DELETE";
export const PERMISSION_TRADE_VIEW = "TRADE_VIEW";
export const PERMISSION_TRADE_EXECUTE = "TRADE_EXECUTE";
export const PERMISSION_TRADE_CANCEL = "TRADE_CANCEL";

// Application Permissions
export const PERMISSION_APPLICATION_CREATE = "APPLICATION_CREATE";
export const PERMISSION_APPLICATION_EDIT = "APPLICATION_EDIT";
export const PERMISSION_APPLICATION_DELETE = "APPLICATION_DELETE";
export const PERMISSION_APPLICATION_VIEW = "APPLICATION_VIEW";
export const PERMISSION_APPLICATION_VIEW_OWN = "APPLICATION_VIEW_OWN";
export const PERMISSION_APPLICATION_SUBMIT = "APPLICATION_SUBMIT";
export const PERMISSION_APPLICATION_APPROVE = "APPLICATION_APPROVE";
export const PERMISSION_APPLICATION_REJECT = "APPLICATION_REJECT";

// Inquiry Permissions
export const PERMISSION_INQUIRY_CREATE = "INQUIRY_CREATE";
export const PERMISSION_INQUIRY_EDIT = "INQUIRY_EDIT";
export const PERMISSION_INQUIRY_VIEW = "INQUIRY_VIEW";
export const PERMISSION_INQUIRY_VIEW_OWN = "INQUIRY_VIEW_OWN";
export const PERMISSION_INQUIRY_RESPOND = "INQUIRY_RESPOND";
export const PERMISSION_INQUIRY_CLOSE = "INQUIRY_CLOSE";

// Template Permissions
export const PERMISSION_TEMPLATE_CREATE = "TEMPLATE_CREATE";
export const PERMISSION_TEMPLATE_EDIT = "TEMPLATE_EDIT";
export const PERMISSION_TEMPLATE_DELETE = "TEMPLATE_DELETE";
export const PERMISSION_TEMPLATE_VIEW = "TEMPLATE_VIEW";
export const PERMISSION_TEMPLATE_GENERATE = "TEMPLATE_GENERATE";

// Payment Permissions
export const PERMISSION_PAYMENT_CREATE = "PAYMENT_CREATE";
export const PERMISSION_PAYMENT_EDIT = "PAYMENT_EDIT";
export const PERMISSION_PAYMENT_DELETE = "PAYMENT_DELETE";
export const PERMISSION_PAYMENT_VIEW = "PAYMENT_VIEW";
export const PERMISSION_PAYMENT_PROCESS = "PAYMENT_PROCESS";

// Financial Permissions
export const PERMISSION_FINANCIAL_VIEW = "FINANCIAL_VIEW";
export const PERMISSION_FINANCIAL_EDIT = "FINANCIAL_EDIT";
export const PERMISSION_FINANCIAL_EXPORT = "FINANCIAL_EXPORT";
export const PERMISSION_FINANCIAL_ANALYZE = "FINANCIAL_ANALYZE";

// Audit Permissions
export const PERMISSION_AUDIT_VIEW = "AUDIT_VIEW";
export const PERMISSION_AUDIT_EXPORT = "AUDIT_EXPORT";
export const PERMISSION_AUDIT_CREATE = "AUDIT_CREATE";

// User Permissions
export const PERMISSION_USER_VIEW = "USER_VIEW";
export const PERMISSION_USER_EDIT = "USER_EDIT";
export const PERMISSION_USER_DELETE = "USER_DELETE";
export const PERMISSION_USER_CREATE = "USER_CREATE";
export const PERMISSION_USER_MANAGE_ROLES = "USER_MANAGE_ROLES";

// Policy Permissions
export const PERMISSION_POLICY_VIEW = "POLICY_VIEW";
export const PERMISSION_POLICY_EDIT = "POLICY_EDIT";
export const PERMISSION_POLICY_CREATE = "POLICY_CREATE";
export const PERMISSION_POLICY_DELETE = "POLICY_DELETE";
export const PERMISSION_POLICY_APPROVE = "POLICY_APPROVE";
export const PERMISSION_POLICY_REJECT = "POLICY_REJECT";
export const PERMISSION_POLICY_VIEW_PENDING = "POLICY_VIEW_PENDING";
export const PERMISSION_POLICY_TEST = "POLICY_TEST";

// Satellite Permissions
export const PERMISSION_SATELLITE_VIEW = "SATELLITE_VIEW";
export const PERMISSION_SATELLITE_VERIFY = "SATELLITE_VERIFY";
export const PERMISSION_SATELLITE_EXPORT = "SATELLITE_EXPORT";

// Export Permissions
export const PERMISSION_EXPORT_DATA = "EXPORT_DATA";
export const PERMISSION_EXPORT_REPORTS = "EXPORT_REPORTS";

// User Roles
export type UserRole = 
  | "auditor"
  | "banker"
  | "law_officer"
  | "accountant"
  | "applicant"
  | "viewer"
  | "analyst"
  | "reviewer"
  | "admin";

export const UserRole = {
  AUDITOR: "auditor" as const,
  BANKER: "banker" as const,
  LAW_OFFICER: "law_officer" as const,
  ACCOUNTANT: "accountant" as const,
  APPLICANT: "applicant" as const,
  VIEWER: "viewer" as const,
  ANALYST: "analyst" as const,
  REVIEWER: "reviewer" as const,
  ADMIN: "admin" as const,
};

// Role Permission Mappings (must match backend)
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  // Auditor: Full oversight, read-only access to all
  [UserRole.AUDITOR]: [
    PERMISSION_DOCUMENT_VIEW,
    PERMISSION_DEAL_VIEW,
    PERMISSION_TRADE_VIEW,
    PERMISSION_APPLICATION_VIEW,
    PERMISSION_INQUIRY_VIEW,
    PERMISSION_TEMPLATE_VIEW,
    PERMISSION_PAYMENT_VIEW,
    PERMISSION_FINANCIAL_VIEW,
    PERMISSION_USER_VIEW,
    PERMISSION_POLICY_VIEW,
    PERMISSION_SATELLITE_VIEW,
    PERMISSION_AUDIT_VIEW,
    PERMISSION_AUDIT_EXPORT,
    PERMISSION_AUDIT_CREATE,
    PERMISSION_DOCUMENT_EXPORT,
    PERMISSION_EXPORT_DATA,
    PERMISSION_EXPORT_REPORTS,
    PERMISSION_SATELLITE_EXPORT,
  ],
  
  // Banker: Write permissions for deals, documents, trades
  [UserRole.BANKER]: [
    PERMISSION_DOCUMENT_CREATE,
    PERMISSION_DOCUMENT_EDIT,
    PERMISSION_DOCUMENT_VIEW,
    PERMISSION_DOCUMENT_EXTRACT,
    PERMISSION_DOCUMENT_EXPORT,
    PERMISSION_DEAL_CREATE,
    PERMISSION_DEAL_EDIT,
    PERMISSION_DEAL_VIEW,
    PERMISSION_DEAL_APPROVE,
    PERMISSION_DEAL_REJECT,
    PERMISSION_DEAL_CLOSE,
    PERMISSION_TRADE_CREATE,
    PERMISSION_TRADE_EDIT,
    PERMISSION_TRADE_VIEW,
    PERMISSION_TRADE_EXECUTE,
    PERMISSION_TRADE_CANCEL,
    PERMISSION_APPLICATION_VIEW,
    PERMISSION_APPLICATION_APPROVE,
    PERMISSION_APPLICATION_REJECT,
    PERMISSION_TEMPLATE_VIEW,
    PERMISSION_TEMPLATE_GENERATE,
    PERMISSION_INQUIRY_VIEW,
    PERMISSION_PAYMENT_VIEW,
    PERMISSION_FINANCIAL_VIEW,
    PERMISSION_POLICY_VIEW,
    PERMISSION_SATELLITE_VIEW,
  ],
  
  // Law Officer: Write/edit for legal documents
  [UserRole.LAW_OFFICER]: [
    PERMISSION_DOCUMENT_CREATE,
    PERMISSION_DOCUMENT_EDIT,
    PERMISSION_DOCUMENT_VIEW,
    PERMISSION_DOCUMENT_REVIEW,
    PERMISSION_DOCUMENT_EXPORT,
    PERMISSION_TEMPLATE_CREATE,
    PERMISSION_TEMPLATE_EDIT,
    PERMISSION_TEMPLATE_VIEW,
    PERMISSION_TEMPLATE_GENERATE,
    PERMISSION_DEAL_VIEW,
    PERMISSION_DEAL_EDIT,
    PERMISSION_APPLICATION_VIEW,
    PERMISSION_INQUIRY_VIEW,
    PERMISSION_POLICY_VIEW,
  ],
  
  // Accountant: Write/edit for financial data
  [UserRole.ACCOUNTANT]: [
    PERMISSION_PAYMENT_CREATE,
    PERMISSION_PAYMENT_EDIT,
    PERMISSION_PAYMENT_VIEW,
    PERMISSION_PAYMENT_PROCESS,
    PERMISSION_FINANCIAL_VIEW,
    PERMISSION_FINANCIAL_EDIT,
    PERMISSION_FINANCIAL_EXPORT,
    PERMISSION_FINANCIAL_ANALYZE,
    PERMISSION_DOCUMENT_VIEW,
    PERMISSION_DOCUMENT_EXPORT,
    PERMISSION_DEAL_VIEW,
    PERMISSION_APPLICATION_VIEW,
    PERMISSION_INQUIRY_VIEW,
    PERMISSION_TEMPLATE_VIEW,
  ],
  
  // Applicant: Apply and track applications
  [UserRole.APPLICANT]: [
    PERMISSION_APPLICATION_CREATE,
    PERMISSION_APPLICATION_EDIT,
    PERMISSION_APPLICATION_VIEW_OWN,
    PERMISSION_APPLICATION_SUBMIT,
    PERMISSION_DEAL_VIEW_OWN,
    PERMISSION_INQUIRY_CREATE,
    PERMISSION_INQUIRY_VIEW_OWN,
    PERMISSION_DOCUMENT_VIEW,
    PERMISSION_TEMPLATE_VIEW,
  ],
  
  // Legacy roles for backward compatibility
  [UserRole.VIEWER]: [
    PERMISSION_DOCUMENT_VIEW,
    PERMISSION_DEAL_VIEW,
    PERMISSION_TRADE_VIEW,
    PERMISSION_APPLICATION_VIEW,
    PERMISSION_TEMPLATE_VIEW,
  ],
  
  [UserRole.ANALYST]: [
    PERMISSION_DOCUMENT_CREATE,
    PERMISSION_DOCUMENT_EDIT,
    PERMISSION_DOCUMENT_VIEW,
    PERMISSION_DOCUMENT_EXTRACT,
    PERMISSION_DEAL_VIEW,
    PERMISSION_TRADE_VIEW,
    PERMISSION_APPLICATION_VIEW,
    PERMISSION_TEMPLATE_VIEW,
    PERMISSION_TEMPLATE_GENERATE,
    PERMISSION_FINANCIAL_VIEW,
    PERMISSION_SATELLITE_VIEW,
  ],
  
  [UserRole.REVIEWER]: [
    PERMISSION_DOCUMENT_VIEW,
    PERMISSION_DOCUMENT_REVIEW,
    PERMISSION_DOCUMENT_APPROVE,
    PERMISSION_DEAL_VIEW,
    PERMISSION_DEAL_APPROVE,
    PERMISSION_APPLICATION_VIEW,
    PERMISSION_APPLICATION_APPROVE,
    PERMISSION_TEMPLATE_VIEW,
    PERMISSION_POLICY_VIEW,
  ],
  
  [UserRole.ADMIN]: [
    // Admin has all permissions
    PERMISSION_DOCUMENT_CREATE,
    PERMISSION_DOCUMENT_EDIT,
    PERMISSION_DOCUMENT_DELETE,
    PERMISSION_DOCUMENT_VIEW,
    PERMISSION_DOCUMENT_REVIEW,
    PERMISSION_DOCUMENT_APPROVE,
    PERMISSION_DOCUMENT_EXPORT,
    PERMISSION_DOCUMENT_EXTRACT,
    PERMISSION_DEAL_CREATE,
    PERMISSION_DEAL_EDIT,
    PERMISSION_DEAL_DELETE,
    PERMISSION_DEAL_VIEW,
    PERMISSION_DEAL_VIEW_OWN,
    PERMISSION_DEAL_APPROVE,
    PERMISSION_DEAL_REJECT,
    PERMISSION_DEAL_CLOSE,
    PERMISSION_TRADE_CREATE,
    PERMISSION_TRADE_EDIT,
    PERMISSION_TRADE_DELETE,
    PERMISSION_TRADE_VIEW,
    PERMISSION_TRADE_EXECUTE,
    PERMISSION_TRADE_CANCEL,
    PERMISSION_APPLICATION_CREATE,
    PERMISSION_APPLICATION_EDIT,
    PERMISSION_APPLICATION_DELETE,
    PERMISSION_APPLICATION_VIEW,
    PERMISSION_APPLICATION_VIEW_OWN,
    PERMISSION_APPLICATION_SUBMIT,
    PERMISSION_APPLICATION_APPROVE,
    PERMISSION_APPLICATION_REJECT,
    PERMISSION_INQUIRY_CREATE,
    PERMISSION_INQUIRY_EDIT,
    PERMISSION_INQUIRY_VIEW,
    PERMISSION_INQUIRY_VIEW_OWN,
    PERMISSION_INQUIRY_RESPOND,
    PERMISSION_INQUIRY_CLOSE,
    PERMISSION_TEMPLATE_CREATE,
    PERMISSION_TEMPLATE_EDIT,
    PERMISSION_TEMPLATE_DELETE,
    PERMISSION_TEMPLATE_VIEW,
    PERMISSION_TEMPLATE_GENERATE,
    PERMISSION_PAYMENT_CREATE,
    PERMISSION_PAYMENT_EDIT,
    PERMISSION_PAYMENT_DELETE,
    PERMISSION_PAYMENT_VIEW,
    PERMISSION_PAYMENT_PROCESS,
    PERMISSION_FINANCIAL_VIEW,
    PERMISSION_FINANCIAL_EDIT,
    PERMISSION_FINANCIAL_EXPORT,
    PERMISSION_FINANCIAL_ANALYZE,
    PERMISSION_AUDIT_VIEW,
    PERMISSION_AUDIT_EXPORT,
    PERMISSION_AUDIT_CREATE,
    PERMISSION_USER_VIEW,
    PERMISSION_USER_EDIT,
    PERMISSION_USER_DELETE,
    PERMISSION_USER_CREATE,
    PERMISSION_USER_MANAGE_ROLES,
    PERMISSION_POLICY_VIEW,
    PERMISSION_POLICY_EDIT,
    PERMISSION_POLICY_CREATE,
    PERMISSION_POLICY_DELETE,
    PERMISSION_POLICY_APPROVE,
    PERMISSION_POLICY_TEST,
    PERMISSION_SATELLITE_VIEW,
    PERMISSION_SATELLITE_VERIFY,
    PERMISSION_SATELLITE_EXPORT,
    PERMISSION_EXPORT_DATA,
    PERMISSION_EXPORT_REPORTS,
  ],
};

/**
 * Get permissions for a given role.
 */
export function getRolePermissions(role: string): string[] {
  return ROLE_PERMISSIONS[role] || [];
}

/**
 * Check if a role has a specific permission.
 */
export function roleHasPermission(role: string, permission: string): boolean {
  const rolePerms = getRolePermissions(role);
  return rolePerms.includes(permission);
}

/**
 * Check if a role has any of the specified permissions.
 */
export function roleHasAnyPermission(role: string, permissions: string[]): boolean {
  const rolePerms = getRolePermissions(role);
  return permissions.some(perm => rolePerms.includes(perm));
}

/**
 * Check if a role has all of the specified permissions.
 */
export function roleHasAllPermissions(role: string, permissions: string[]): boolean {
  const rolePerms = getRolePermissions(role);
  return permissions.every(perm => rolePerms.includes(perm));
}
