"""
Script to seed demo users with different roles for CreditNexus application.

Usage:
    Set environment variables to control which users are seeded:
    - SEED_DEMO_USERS=true (enables seeding)
    - SEED_AUDITOR=true (seed auditor user)
    - SEED_BANKER=true (seed banker user)
    - SEED_LAW_OFFICER=true (seed law officer user)
    - SEED_ACCOUNTANT=true (seed accountant user)
    - SEED_APPLICANT=true (seed applicant user)
    
    Or run directly:
    python scripts/seed_demo_users.py
    uv run python scripts/seed_demo_users.py
"""

import sys
import os
import logging
import random
from pathlib import Path
from datetime import datetime, date

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.db import SessionLocal, init_db
from app.db.models import User, UserRole
from app.auth.jwt_auth import get_password_hash

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Demo user definitions with comprehensive profile data
# Note: profile_data will be generated using helper functions below
DEMO_USERS = [
    {
        "email": "auditor@creditnexus.app",
        "password": "Auditor123!",
        "display_name": "Demo Auditor",
        "role": UserRole.AUDITOR,
        "profile_data": None  # Will be generated by _generate_comprehensive_profile_data
    },
    {
        "email": "banker@creditnexus.app",
        "password": "Banker123!",
        "display_name": "Demo Banker",
        "role": UserRole.BANKER,
        "profile_data": None  # Will be generated by _generate_comprehensive_profile_data
    },
    {
        "email": "lawofficer@creditnexus.app",
        "password": "LawOfficer123!",
        "display_name": "Demo Law Officer",
        "role": UserRole.LAW_OFFICER,
        "profile_data": None  # Will be generated by _generate_comprehensive_profile_data
    },
    {
        "email": "accountant@creditnexus.app",
        "password": "Accountant123!",
        "display_name": "Demo Accountant",
        "role": UserRole.ACCOUNTANT,
        "profile_data": None  # Will be generated by _generate_comprehensive_profile_data
    },
    {
        "email": "applicant@creditnexus.app",
        "password": "Applicant123!",
        "display_name": "Demo Applicant",
        "role": UserRole.APPLICANT,
        "profile_data": None  # Will be generated by _generate_comprehensive_profile_data
    },
]


def _generate_personal_info(role: UserRole) -> dict:
    """Generate personal information based on role."""
    first_names = {
        UserRole.AUDITOR: ["Sarah", "Michael", "Jennifer", "David"],
        UserRole.BANKER: ["James", "Emily", "Robert", "Jessica"],
        UserRole.LAW_OFFICER: ["Patricia", "William", "Linda", "Richard"],
        UserRole.ACCOUNTANT: ["Elizabeth", "Thomas", "Barbara", "Charles"],
        UserRole.APPLICANT: ["John", "Mary", "Joseph", "Susan"]
    }
    last_names = {
        UserRole.AUDITOR: ["Anderson", "Martinez", "Thompson", "Garcia"],
        UserRole.BANKER: ["Wilson", "Moore", "Taylor", "Jackson"],
        UserRole.LAW_OFFICER: ["White", "Harris", "Martin", "Clark"],
        UserRole.ACCOUNTANT: ["Lewis", "Robinson", "Walker", "Young"],
        UserRole.APPLICANT: ["Smith", "Johnson", "Williams", "Brown"]
    }
    
    first_name = random.choice(first_names.get(role, ["John"]))
    last_name = random.choice(last_names.get(role, ["Doe"]))
    full_name = f"{first_name} {last_name}"
    
    # Generate date of birth (age 25-65)
    age = random.randint(25, 65)
    birth_year = datetime.now().year - age
    birth_month = random.randint(1, 12)
    birth_day = random.randint(1, 28)  # Use 28 to avoid month-end issues
    date_of_birth = date(birth_year, birth_month, birth_day)
    
    nationalities = ["US", "UK", "CA", "AU", "DE", "FR"]
    nationality = random.choice(nationalities)
    
    return {
        "first_name": first_name,
        "last_name": last_name,
        "full_name": full_name,
        "date_of_birth": date_of_birth.isoformat(),
        "nationality": nationality
    }


def _generate_contact_info(role: UserRole, email: str) -> dict:
    """Generate contact information based on role."""
    # Generate phone numbers
    area_code = random.randint(200, 999)
    exchange = random.randint(200, 999)
    number = random.randint(1000, 9999)
    phone = f"+1-{area_code}-{exchange}-{number:04d}"
    mobile = f"+1-{area_code}-{exchange}-{random.randint(1000, 9999):04d}"
    fax = f"+1-{area_code}-{exchange}-{random.randint(1000, 9999):04d}"
    
    # Generate LinkedIn URL
    first_name = email.split("@")[0].split(".")[0] if "." in email.split("@")[0] else email.split("@")[0]
    linkedin = f"https://linkedin.com/in/{first_name.lower()}-{role.value.lower()}"
    
    # Generate website (for applicants and companies)
    if role == UserRole.APPLICANT:
        website = f"https://www.{first_name.lower()}corp.com"
    else:
        website = None
    
    return {
        "phone": phone,
        "mobile": mobile,
        "fax": fax,
        "email": email,
        "linkedin": linkedin,
        "website": website
    }


def _generate_professional_info(role: UserRole) -> dict:
    """Generate professional information based on role."""
    job_titles = {
        UserRole.AUDITOR: ["Senior Auditor", "Lead Auditor", "Audit Manager", "Principal Auditor"],
        UserRole.BANKER: ["Credit Analyst", "Senior Credit Analyst", "Relationship Manager", "VP of Credit"],
        UserRole.LAW_OFFICER: ["Senior Legal Counsel", "Legal Director", "Associate General Counsel", "Legal Advisor"],
        UserRole.ACCOUNTANT: ["Senior Accountant", "Accounting Manager", "Financial Controller", "CFO"],
        UserRole.APPLICANT: ["Business Owner", "CEO", "President", "Founder"]
    }
    
    departments = {
        UserRole.AUDITOR: "Audit Department",
        UserRole.BANKER: "Credit Department",
        UserRole.LAW_OFFICER: "Legal Department",
        UserRole.ACCOUNTANT: "Finance Department",
        UserRole.APPLICANT: None
    }
    
    certifications = {
        UserRole.AUDITOR: ["CPA", "CIA", "CISA", "CFE"],
        UserRole.BANKER: ["CFA", "FRM", "CAIA"],
        UserRole.LAW_OFFICER: ["JD", "LLM"],
        UserRole.ACCOUNTANT: ["CPA", "CMA", "CFA"],
        UserRole.APPLICANT: []
    }
    
    licenses = {
        UserRole.BANKER: ["Series 7", "Series 63", "Series 79"],
        UserRole.LAW_OFFICER: ["Bar Admission (NY)", "Bar Admission (CA)", "Bar Admission (TX)"],
        UserRole.ACCOUNTANT: ["CPA License"],
        UserRole.AUDITOR: ["CPA License"],
        UserRole.APPLICANT: []
    }
    
    specializations = {
        UserRole.AUDITOR: ["Financial Auditing", "Compliance Auditing", "Internal Controls"],
        UserRole.BANKER: ["Corporate Lending", "Credit Risk", "Structured Finance"],
        UserRole.LAW_OFFICER: ["Corporate Law", "Securities Law", "Contract Law"],
        UserRole.ACCOUNTANT: ["Financial Reporting", "Tax Planning", "Management Accounting"],
        UserRole.APPLICANT: []
    }
    
    job_title = random.choice(job_titles.get(role, ["Professional"]))
    department = departments.get(role)
    years_of_experience = random.randint(3, 25)
    
    certs = certifications.get(role, [])
    selected_certs = random.sample(certs, min(len(certs), random.randint(1, 2))) if certs else []
    
    lic = licenses.get(role, [])
    selected_licenses = random.sample(lic, min(len(lic), random.randint(1, 2))) if lic else []
    
    specs = specializations.get(role, [])
    selected_specs = random.sample(specs, min(len(specs), random.randint(1, 2))) if specs else []
    
    return {
        "job_title": job_title,
        "department": department,
        "years_of_experience": years_of_experience,
        "certifications": selected_certs,
        "licenses": selected_licenses,
        "specializations": selected_specs
    }


def _generate_company_info(role: UserRole) -> dict:
    """Generate company information based on role."""
    if role == UserRole.APPLICANT:
        company_names = ["ACME Corporation", "Global Industries Inc.", "Premier Business Solutions", "Advanced Systems LLC"]
        legal_names = ["ACME Corporation, Inc.", "Global Industries Incorporated", "Premier Business Solutions LLC", "Advanced Systems, LLC"]
        industries = ["Technology", "Manufacturing", "Services", "Retail"]
    else:
        company_names = {
            UserRole.AUDITOR: "CreditNexus Audit Department",
            UserRole.BANKER: "CreditNexus Bank",
            UserRole.LAW_OFFICER: "CreditNexus Legal Department",
            UserRole.ACCOUNTANT: "CreditNexus Finance Department"
        }
        legal_names = company_names
        industries = ["Financial Services"]
    
    company_name = random.choice(company_names) if isinstance(company_names, list) else company_names.get(role, "CreditNexus")
    legal_name = random.choice(legal_names) if isinstance(legal_names, list) else legal_names.get(role, company_name)
    
    registration_number = f"REG-{random.randint(100000, 999999)}"
    tax_id = f"{random.randint(10, 99)}-{random.randint(1000000, 9999999)}"
    lei = f"98{random.randint(1000000000000000, 9999999999999999)}"
    
    industry = random.choice(industries) if isinstance(industries, list) else industries
    
    addresses = {
        UserRole.AUDITOR: {"street": "123 Audit Street", "city": "New York", "state": "NY", "postal_code": "10001", "country": "US"},
        UserRole.BANKER: {"street": "456 Banking Avenue", "city": "New York", "state": "NY", "postal_code": "10005", "country": "US"},
        UserRole.LAW_OFFICER: {"street": "789 Legal Boulevard", "city": "New York", "state": "NY", "postal_code": "10010", "country": "US"},
        UserRole.ACCOUNTANT: {"street": "321 Finance Way", "city": "New York", "state": "NY", "postal_code": "10015", "country": "US"},
        UserRole.APPLICANT: {"street": "654 Business Road", "city": "New York", "state": "NY", "postal_code": "10020", "country": "US"}
    }
    
    address = addresses.get(role, addresses[UserRole.APPLICANT])
    full_address = f"{address['street']}, {address['city']}, {address['state']} {address['postal_code']}"
    
    website = f"https://www.{company_name.lower().replace(' ', '').replace(',', '')}.com" if role == UserRole.APPLICANT else "https://www.creditnexus.app"
    
    return {
        "name": company_name,
        "legal_name": legal_name,
        "registration_number": registration_number,
        "tax_id": tax_id,
        "lei": lei,
        "industry": industry,
        "website": website,
        "address": {
            **address,
            "full_address": full_address
        }
    }


def _generate_financial_info(role: UserRole) -> dict:
    """Generate financial information based on role."""
    if role == UserRole.APPLICANT:
        # Applicants have business financials
        annual_revenue = random.uniform(500000, 50000000)
        aum = None
        credit_ratings = ["BBB", "BB", "B", "CCC"]
        credit_rating_agencies = ["S&P", "Moody's", "Fitch"]
    elif role in [UserRole.BANKER, UserRole.ACCOUNTANT]:
        # Financial professionals may have AUM
        annual_revenue = None
        aum = random.uniform(10000000, 1000000000)
        credit_ratings = ["AAA", "AA", "A"]
        credit_rating_agencies = ["S&P", "Moody's"]
    else:
        # Other roles don't have financial info
        return {}
    
    currency = "USD"
    credit_rating = random.choice(credit_ratings) if credit_ratings else None
    credit_rating_agency = random.choice(credit_rating_agencies) if credit_rating_agencies else None
    
    result = {
        "revenue_currency": currency if annual_revenue else None,
        "aum_currency": currency if aum else None,
        "credit_rating": credit_rating,
        "credit_rating_agency": credit_rating_agency
    }
    
    if annual_revenue:
        result["annual_revenue"] = annual_revenue
    if aum:
        result["assets_under_management"] = aum
    
    return result


def _generate_role_specific_data(role: UserRole) -> dict:
    """Generate role-specific data."""
    if role == UserRole.AUDITOR:
        return {
            "audit_certifications": ["ISO 27001 Lead Auditor", "SOC 2 Type II"],
            "audit_experience_years": random.randint(5, 20),
            "industries_audited": random.sample(["Banking", "Technology", "Healthcare", "Manufacturing"], random.randint(2, 4))
        }
    elif role == UserRole.BANKER:
        return {
            "banking_licenses": ["Series 7", "Series 63"],
            "credit_committee_member": random.choice([True, False]),
            "portfolio_size": random.uniform(50000000, 500000000)
        }
    elif role == UserRole.ACCOUNTANT:
        return {
            "firm_name": "CreditNexus Finance Department",
            "cpa_license_number": f"CPA-{random.randint(10000, 99999)}",
            "tax_specialization": random.choice(["Corporate Tax", "Individual Tax", "International Tax"])
        }
    elif role == UserRole.APPLICANT:
        return {
            "business_type": random.choice(["LLC", "Corporation", "Partnership"]),
            "years_in_business": random.randint(1, 20),
            "number_of_employees": random.randint(10, 500)
        }
    else:
        return {}


def _generate_comprehensive_profile_data(role: UserRole, email: str) -> dict:
    """Generate comprehensive profile data for a user role."""
    personal = _generate_personal_info(role)
    contact = _generate_contact_info(role, email)
    professional = _generate_professional_info(role)
    company = _generate_company_info(role)
    financial = _generate_financial_info(role)
    role_specific = _generate_role_specific_data(role)
    
    return {
        **personal,
        "contact": contact,
        "personal_address": company.get("address"),  # Use company address as personal for demo
        "professional": professional,
        "company": company,
        "financial": financial if financial else None,
        "role_specific_data": role_specific if role_specific else None,
        "extracted_from": "demo_seeding",
        "extraction_confidence": 1.0,
        "extraction_date": datetime.now().isoformat(),
        "raw_extracted_text": f"Demo profile data for {role.value} role"
    }


def seed_demo_users(db, force: bool = False, seed_all_roles: bool = True) -> int:
    """
    Seed demo users into database.
    
    Args:
        db: Database session
        force: If True, update existing users. If False, skip existing users.
        seed_all_roles: If True, seed all roles regardless of environment flags. 
                       If False, check environment flags. Default True for API calls.
        
    Returns:
        Number of users created/updated
    """
    created_count = 0
    updated_count = 0
    
    # Check which users to seed based on environment flags (only if seed_all_roles=False)
    if seed_all_roles:
        # When called from API, seed all users by default
        seed_all = True
        seed_auditor = True
        seed_banker = True
        seed_law_officer = True
        seed_accountant = True
        seed_applicant = True
    else:
        # When called from command line, check environment variables
        seed_all = os.getenv("SEED_DEMO_USERS", "false").lower() == "true"
        seed_auditor = os.getenv("SEED_AUDITOR", "false").lower() == "true"
        seed_banker = os.getenv("SEED_BANKER", "false").lower() == "true"
        seed_law_officer = os.getenv("SEED_LAW_OFFICER", "false").lower() == "true"
        seed_accountant = os.getenv("SEED_ACCOUNTANT", "false").lower() == "true"
        seed_applicant = os.getenv("SEED_APPLICANT", "false").lower() == "true"
    
    # Role flag mapping
    role_flags = {
        UserRole.AUDITOR: seed_auditor,
        UserRole.BANKER: seed_banker,
        UserRole.LAW_OFFICER: seed_law_officer,
        UserRole.ACCOUNTANT: seed_accountant,
        UserRole.APPLICANT: seed_applicant,
    }
    
    for user_data in DEMO_USERS:
        role = user_data["role"]
        
        # Check if this user should be seeded
        if not seed_all and not role_flags.get(role, False):
            logger.debug(f"Skipping {user_data['email']} (not enabled via environment flags)")
            continue
        
        # Generate comprehensive profile data if not already set
        if user_data.get("profile_data") is None:
            user_data["profile_data"] = _generate_comprehensive_profile_data(role, user_data["email"])
        
        # Check if user already exists
        existing_user = db.query(User).filter(User.email == user_data["email"]).first()
        
        if existing_user:
            if force:
                # Update existing user
                existing_user.display_name = user_data["display_name"]
                existing_user.role = role.value
                existing_user.profile_data = user_data.get("profile_data")
                existing_user.is_active = True
                existing_user.is_email_verified = True
                db.commit()
                updated_count += 1
                logger.info(f"Updated user: {user_data['email']}")
            else:
                logger.debug(f"User {user_data['email']} already exists, skipping")
            continue
        
        try:
            # Create new user
            user = User(
                email=user_data["email"],
                password_hash=get_password_hash(user_data["password"]),
                display_name=user_data["display_name"],
                role=role.value,
                profile_data=user_data.get("profile_data"),
                is_active=True,
                is_email_verified=True,  # Mark as verified for convenience
            )
            db.add(user)
            db.commit()
            db.refresh(user)
            created_count += 1
            logger.info(f"Created user: {user_data['email']} ({role.value})")
        except Exception as e:
            logger.error(f"Failed to seed user {user_data['email']}: {e}")
            db.rollback()
            continue
    
    logger.info(f"User seeding complete: {created_count} created, {updated_count} updated")
    return created_count + updated_count


def main():
    """Main function to seed demo users."""
    # Check if seeding is enabled
    seed_enabled = os.getenv("SEED_DEMO_USERS", "false").lower() == "true"
    force = os.getenv("SEED_DEMO_USERS_FORCE", "false").lower() == "true"
    
    # Also check individual role flags
    has_role_flags = any([
        os.getenv("SEED_AUDITOR", "false").lower() == "true",
        os.getenv("SEED_BANKER", "false").lower() == "true",
        os.getenv("SEED_LAW_OFFICER", "false").lower() == "true",
        os.getenv("SEED_ACCOUNTANT", "false").lower() == "true",
        os.getenv("SEED_APPLICANT", "false").lower() == "true",
    ])
    
    if not seed_enabled and not has_role_flags:
        logger.info("User seeding is disabled. Set SEED_DEMO_USERS=true or individual role flags to enable.")
        return
    
    logger.info("Starting demo user seeding...")
    
    # Initialize database
    init_db()
    db = SessionLocal()
    
    try:
        user_count = seed_demo_users(db, force=force)
        
        if user_count > 0:
            logger.info(f"Demo user seeding complete: {user_count} user(s) processed")
            logger.info("=" * 60)
            logger.info("Demo user credentials:")
            for user_data in DEMO_USERS:
                logger.info(f"  {user_data['email']} / {user_data['password']} ({user_data['role'].value})")
            logger.info("=" * 60)
        else:
            logger.info("All demo users already exist in database")
    except Exception as e:
        logger.error(f"Error during user seeding: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    main()
